### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by ghost** [2044-space-elevator/OnlineJudgeCode#1]
洛谷常会获取其他OJ题目（`remotejudge`）,这时应该归类至原OJ而非洛谷，或在两个OJ中均有一份

e.g.  [这一道CF1844D](https://github.com/2044-space-elevator/OnlineJudgeCode/blob/main/Luogu/CF1844D.cpp)应该归类为[Codeforces](https://codeforces.com/problemset/problem/1844/D)或是既有[洛谷](https://www.luogu.com.cn/problem/CF1844D)又有[Codeforces](https://codeforces.com/problemset/problem/1844/D)(在洛谷题目边栏`题目来源`选项卡的超链接可以直接引导到原题的URL)

**Comment by 2044-space-elevator** [comment]
> 洛谷常会获取其他OJ题目（`remotejudge`）,这时应该归类至原OJ而非洛谷，或在两个OJ中均有一份
> 
> e.g. [这一道CF1844D](https://github.com/2044-space-elevator/OnlineJudgeCode/blob/main/Luogu/CF1844D.cpp)应该归类为[Codeforces](https://codeforces.com/problemset/problem/1844/D)或是既有[洛谷](https://www.luogu.com.cn/problem/CF1844D)又有[Codeforces](https://codeforces.com/problemset/problem/1844/D)(在洛谷题目边栏`题目来源`选项卡的超链接可以直接引导到原题的URL)

应该没有必要分类如此详细？

好吧，改一下。

另外我个人的储存库其实没必要这么较真，更没必要提 issue
